<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Forma de Pago_payment_opc</name>
   <tag></tag>
   <elementGuidId>389c66a5-0e17-47b7-bcea-69dcbbd2c239</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opc_paymentMethod > h6.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h6[@class='opc_paymentMethod_title liverpool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>1039ba71-02ef-4cc2-942c-93dd8c8983d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>61602a95-8d74-44dd-bb6c-dbfee66c5b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2. Forma de Pago</value>
      <webElementGuid>4964e497-f133-4848-9640-c7baf7513fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc_paymentMethod&quot;)/h6[@class=&quot;undefined&quot;]</value>
      <webElementGuid>77d8aa29-f9b4-4af0-b51c-fb1804a95fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc_paymentMethod']/h6</value>
      <webElementGuid>687b72f2-3f80-4054-8d0e-914278f67fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar'])[1]/following::h6[1]</value>
      <webElementGuid>a811b26f-c6df-44c8-ad8d-ddb03a2d2b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*9488'])[1]/preceding::h6[1]</value>
      <webElementGuid>41034b0d-bfcd-4d91-8e11-3505ed86ff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2. Forma de Pago']/parent::*</value>
      <webElementGuid>b6dc7a7f-4982-4b98-a04f-0830b1769831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h6</value>
      <webElementGuid>ef5e6174-0d23-497b-a840-3ee617a5cc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = '2. Forma de Pago' or . = '2. Forma de Pago')]</value>
      <webElementGuid>ec16f55c-103b-49df-a274-b674745307b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
