<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Service</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a341f929-7dac-4306-aab6-e7538e97e7fa</testSuiteGuid>
   <testCaseLink>
      <guid>2f4fe145-5d2a-438d-9fd8-625ff474f36c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LiverpoolDemo1/AccountManagement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>539093bc-9142-49d9-b718-96b9b37ddd47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc0211fa-a75f-4a7c-b76c-ad25e60e30e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1482d6a0-bcde-4022-ba6b-5b83251feb1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3127308-5348-400e-923b-74c5c72c80bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>848a2715-dfee-4c63-8704-9fee0fe89a14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d64bdb2a-b8f9-44c9-8de4-ab4b56882c5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5383ac73-bbed-4aef-8a34-6a833ba4c738</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9c51819-3388-46eb-aed9-b9f097d751e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11cd7670-f47f-473e-b0c7-5115c47962da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>204ca349-e478-42f1-bb3a-4a7cd57bf4c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd9ed6c8-7e69-4b3d-a97a-a6a5d6b56221</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0feb98df-85ff-4b57-affe-6fef14e56b02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>972789c3-e715-4dc9-997d-810a445b80f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LiverpoolDemo1/BrowseAndShop</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7331ecf-ebef-4467-90a9-9d264a71950d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112d0084-3906-4953-8183-320cc81361d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ab6a8ae-b01d-4f5c-8985-5126268531fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dce8af0-b4bc-4985-beea-7265fc7c9485</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aff5395b-d590-4536-b232-f0fc613e3f38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LiverpoolDemo1/OrderReview</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6a64b83-b9e7-4075-ba0d-23e61280aa29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2dab2f6-95fc-4610-a99d-4f8260bf8b53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7e6b3f2-cc1a-4c1c-9200-b8fc12d444ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47634487-fcef-4a56-9e72-7df1dc901fc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>027ea448-e8eb-478b-83b5-b6928c9e893a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c5cc8b6-41e5-47b3-a849-6266673f2dc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LiverpoolDemo1/Liverpool-loginwithinvalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>756a5e9f-240b-4842-8ec5-094de35783a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c37fd90-e2e9-45e2-8bdd-c9267f91c34e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d46b423-08da-4425-beb6-26657801592c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e82be4b-f325-4e85-974f-61481a1b8028</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LiverpoolDemo1/TC_01_LoginWithAuth</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3d1ca3cc-5ed4-4a1a-998f-44f6e9c96cb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LiverpoolDemo1/Login-MissingAAT</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6e45732e-5969-4dca-a2fb-abb22ed7f5f2</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>21-25</value>
         </iterationEntity>
         <testDataId>Data Files/ServicesTestdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6e45732e-5969-4dca-a2fb-abb22ed7f5f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>correlationid</value>
         <variableId>521bb7cb-29eb-4f8b-9e16-fce50209404c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6e45732e-5969-4dca-a2fb-abb22ed7f5f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AAT</value>
         <variableId>f1e33ce6-c8c1-49fc-a36f-3aaa8aa76c7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6e45732e-5969-4dca-a2fb-abb22ed7f5f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>brand</value>
         <variableId>e1110308-36b2-4e72-8410-ca41fa24ed85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6e45732e-5969-4dca-a2fb-abb22ed7f5f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>channel</value>
         <variableId>2870011c-ba0b-45f2-b78c-ee88476464cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6e45732e-5969-4dca-a2fb-abb22ed7f5f2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>DeviceID</value>
         <variableId>9d7b2b6c-e1f1-484a-bf0f-2da7d9a53174</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
