<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>myBagImageProduct_cart</name>
   <tag></tag>
   <elementGuidId>2cd12f2a-09d2-4af7-8f32-10bcea2202fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.a-myBagImageProduct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//figure[@class='m-imageProductMyBag']//img)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6e3b466e-ef22-4f32-97a1-05b200fc3b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss237.liverpool.com.mx/lg/1111964187.jpg</value>
      <webElementGuid>1e6b92bd-b8f4-495e-94d8-13106d0d75c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>alt-Description</value>
      <webElementGuid>d50242b2-492e-4bd2-bc77-c64914885f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-myBagImageProduct</value>
      <webElementGuid>86c424ce-14c6-4a47-a099-f52c8a006d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nonclickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2537eec0-9dc6-443e-8dcb-b5868b3671b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1111964218&quot;)/div[@class=&quot;o-myBag__column o-myBag__column--triple&quot;]/div[@class=&quot;o-myBag__image&quot;]/figure[@class=&quot;m-imageProductMyBag&quot;]/img[@class=&quot;a-myBagImageProduct&quot;]</value>
      <webElementGuid>e43bb801-dd9a-411d-b3ba-093322b5128e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1111964218']/div/div/figure/img</value>
      <webElementGuid>bc768f47-7e1e-41cc-b843-62c42fc97315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='alt-Description']</value>
      <webElementGuid>e8186844-28c7-4ad8-8c34-3aca8b3fde04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>f1a9bda2-ef1b-4fee-a24f-d1ac5c1caef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss237.liverpool.com.mx/lg/1111964187.jpg' and @alt = 'alt-Description']</value>
      <webElementGuid>6c18b61d-e50a-4eb7-8c1b-c274731ac9db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
