<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Agregar direccin</name>
   <tag></tag>
   <elementGuidId>304456e3-eedb-4c12-9ade-a596c97fe052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[4]/div[2]/section/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.a-btn.a-btn--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Agregar dirección&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b5d46c8-1113-42c6-8976-489824310de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>38017bc8-0f1f-4e45-ab30-0635af6515a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ripple</name>
      <type>Main</type>
      <value>ripple</value>
      <webElementGuid>06d160d2-f173-4378-b830-75cac6d052ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agregar dirección</value>
      <webElementGuid>3ac65697-df2e-49ed-8fd7-73515b38edc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;h-100 row m-row-bootstrap my-lg-3 container-infoAccount&quot;]/div[@class=&quot;gen_sticky-container&quot;]/section[@class=&quot;myAccount-address__header&quot;]/div[@class=&quot;myAccount-address__header__button&quot;]/div[@class=&quot;myAccount-address__header__button__container&quot;]/button[@class=&quot;a-btn a-btn--primary&quot;]</value>
      <webElementGuid>5baa8f88-0f67-499d-b120-68522061e563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[4]/div[2]/section/div[2]/div/button</value>
      <webElementGuid>65f520a4-1c5e-4edc-82c9-d2800a6b2571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiendas Click &amp; Collect'])[1]/following::button[1]</value>
      <webElementGuid>db520224-bef8-40d8-b274-b4d7ba3972f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis direcciones'])[1]/following::button[2]</value>
      <webElementGuid>ba327c5f-1ab6-44b5-9dea-013089762d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sudha1'])[1]/preceding::button[1]</value>
      <webElementGuid>4b7caf24-b432-440f-a25d-7ac594617df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar como predeterminada'])[1]/preceding::button[1]</value>
      <webElementGuid>94dd73f2-5624-4607-8493-7197dc423011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agregar dirección']/parent::*</value>
      <webElementGuid>91258388-b74a-422f-ac3c-903c1912eb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/button</value>
      <webElementGuid>7eef3588-67e7-4e2e-9346-bb6ef4fa528a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Agregar dirección' or . = 'Agregar dirección')]</value>
      <webElementGuid>439c3de1-8ef2-4d6b-a566-8a837abdf465</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
