<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Guardar</name>
   <tag></tag>
   <elementGuidId>2bc68d7d-07f9-4050-bc39-0d923d0345cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div[4]/div[2]/section/div/div[4]/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.a-btn.a-btn--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Guardar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5042227e-0303-432d-9bbf-ba9f39bb62bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-btn a-btn--primary</value>
      <webElementGuid>f6679b39-60b5-4ba9-a67c-90c071f956d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ripple</name>
      <type>Main</type>
      <value>ripple</value>
      <webElementGuid>bc805970-963e-4c10-bd6d-d07d945700fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>5b185b34-3d60-4933-8530-e2ecc9846446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container-fluid o-main-container p-0&quot;]/div[@class=&quot;container o-container__secondary&quot;]/div[@class=&quot;h-100 row m-row-bootstrap my-lg-3 container-infoAccount&quot;]/div[@class=&quot;gen_sticky-container&quot;]/section[@class=&quot;myAccount-address__content address-margin-top&quot;]/div[@class=&quot;m-box o-myAccount__editCards mb-5&quot;]/div[@class=&quot;row mt-4 mb-4&quot;]/div[@class=&quot;col-lg-3 mb-3 order-1 order-lg-2&quot;]/button[@class=&quot;a-btn a-btn--primary&quot;]</value>
      <webElementGuid>a3daa0e8-37ae-4a1b-bc95-3c9a1b7a8ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div[4]/div[2]/section/div/div[4]/div[3]/button</value>
      <webElementGuid>b7d2013a-8b0c-474f-a8a3-8b49f22503ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::button[1]</value>
      <webElementGuid>8cfe02f5-9c59-4c0d-9369-4de868b9f31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos y Condiciones así como las Política de uso de datos'])[1]/following::button[2]</value>
      <webElementGuid>09918d5b-8895-4311-9476-07195972b1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soporte al cliente'])[1]/preceding::button[1]</value>
      <webElementGuid>632f9f17-4d15-41b8-8add-f7bd0bd2d046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facturación'])[2]/preceding::button[1]</value>
      <webElementGuid>f3962921-c4d8-496f-8b48-ee6f4d6d9a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar']/parent::*</value>
      <webElementGuid>918dc33d-5e4f-4802-ac50-64116a07044a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>ef1d7671-2cc4-4b12-9ef9-67ceab6c3268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Guardar' or . = 'Guardar')]</value>
      <webElementGuid>2ef3f9c0-8d95-4bef-a0e4-90f8e7aee0c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
