<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verde Oscuro_mainSearchbar</name>
   <tag></tag>
   <elementGuidId>fbd0a6ef-ae8b-437e-9664-5997254585dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainSearchbar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainSearchbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Buscar por producto, marca y más...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8f8289e-4205-460f-b65b-4c3cfdef410f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainSearchbar</value>
      <webElementGuid>a22d401b-abbf-43d8-b8ab-a7b8c0fd3048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-bar plp-no__results</value>
      <webElementGuid>579ce063-3ca6-4ef2-b669-51f9ad31d26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Buscar por producto, marca y más...</value>
      <webElementGuid>e854f0d3-b35b-4ee0-b736-cebe467c0402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5da4525b-f9e0-4a9a-a37a-1345e4bf5e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar por producto, marca y más...</value>
      <webElementGuid>ee8a609e-d85d-4ccd-9465-8f37fd5ec2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>182d6a1a-a95b-45a6-aefb-6f9fda619ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>vaso</value>
      <webElementGuid>5bdceccc-4666-4935-8eba-8efb9a3ed760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainSearchbar&quot;)</value>
      <webElementGuid>99d10d5f-0080-45f6-a78e-a4ce6beb56e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainSearchbar']</value>
      <webElementGuid>46030442-5696-4129-ae49-1191a10d2333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sayt']/div/div/input</value>
      <webElementGuid>285315db-a58f-4740-9971-1ae9210a2a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>6e12b48c-c66f-4ac3-8340-5df289ce2a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mainSearchbar' and @type = 'text' and @placeholder = 'Buscar por producto, marca y más...']</value>
      <webElementGuid>5f69b69f-1c40-4fee-bafa-d3b1bc742fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
