<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Calificaciones_img_0</name>
   <tag></tag>
   <elementGuidId>f0c879b2-8299-4823-b1ba-b5094ca4bb46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Sofá cama Sofantástico Boxsofa Queen de lino$10,49900$6,99900 (4)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4391a28a-ecc4-4f63-a4bb-84b02a80cc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>a6d97211-5d89-440e-9229-91eb7bf8256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ss101.liverpool.com.mx/sm/1143930391.jpg</value>
      <webElementGuid>84c43762-3565-4f18-8b18-5cc4f8405439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sofá cama Sofantástico Boxsofa Queen de lino</value>
      <webElementGuid>c37480e1-fdff-492b-bb39-a2227b206a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_0</value>
      <webElementGuid>397220c2-8d01-4308-bd23-a54f21861cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_0&quot;)</value>
      <webElementGuid>e96a36a2-eaa0-4085-90bd-c2749098ea2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_0']</value>
      <webElementGuid>b89cab40-a9b4-4ed4-a71e-118be372ba8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/main/div[2]/div/div/ul/li/a/div/figure/div/section/img</value>
      <webElementGuid>b4e48d95-aab9-4d80-9ba2-17de00d4f91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sofá cama Sofantástico Boxsofa Queen de lino']</value>
      <webElementGuid>915b16d8-eb18-425b-b98b-b2a5942d3b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/img</value>
      <webElementGuid>ce4d8eb4-57e9-48f7-9766-dc969f721504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ss101.liverpool.com.mx/sm/1143930391.jpg' and @alt = 'Sofá cama Sofantástico Boxsofa Queen de lino' and @id = 'img_0']</value>
      <webElementGuid>24c1b779-4ae8-4601-869b-ea350fad5a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
