<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Cdigo de Producto_pdp</name>
   <tag></tag>
   <elementGuidId>81e84b5f-9a6f-4003-9551-052dcf59e07e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.m-product__information--code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@class='product-header-subcontainer-information--code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>02454cbf-6ee5-449f-9821-c2c21a432564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-product__information--code</value>
      <webElementGuid>2db6d8c4-6a28-409b-a209-49c6ab7c49cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Código de Producto: 1064348982</value>
      <webElementGuid>720de370-1075-47a1-a76f-02ef4ed39cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;min-vh-100&quot;]/section[@class=&quot;o-product__detail&quot;]/div[@class=&quot;container o-product__mainContainer&quot;]/main[1]/div[@class=&quot;o-product__description&quot;]/p[@class=&quot;m-product__information--code&quot;]</value>
      <webElementGuid>cbfa5315-e1e1-4a78-93f2-9acf4274e681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section/div/main/div[2]/p</value>
      <webElementGuid>969b5669-a224-47f2-b924-41a15ecabf59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenis Puma unisex'])[2]/following::p[1]</value>
      <webElementGuid>e2829a23-20f8-47e8-be57-4902777d8f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenis'])[1]/following::p[1]</value>
      <webElementGuid>1ff24f46-090b-4f67-bcdf-8ac1375becf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escribe una opinión'])[1]/preceding::p[1]</value>
      <webElementGuid>74bfa210-7207-446c-bf13-c733879e5db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver disponibilidad en tienda'])[1]/preceding::p[1]</value>
      <webElementGuid>c78a9cc2-6b78-4104-81fc-2b56e0fa377e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Código de Producto:']/parent::*</value>
      <webElementGuid>14b4da8a-ad1a-4eac-b1c8-51cb8d99128f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>edb0dade-9b66-483d-8881-f906c4a3f5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Código de Producto: 1064348982' or . = 'Código de Producto: 1064348982')]</value>
      <webElementGuid>c702ab26-ed01-4836-ac17-1d49bfa627bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
