<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Toys R Us_mainSearchbar</name>
   <tag></tag>
   <elementGuidId>34459e55-0b68-4279-8876-bcbb12dfd6a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainSearchbar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainSearchbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Buscar por producto, marca y más...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25dcfd7c-2f06-40f5-8a12-ea30993fa761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainSearchbar</value>
      <webElementGuid>6a738cd6-98aa-4fda-aa63-e20c56212ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-bar plp-no__results</value>
      <webElementGuid>82e22dca-6fd0-41a0-ad2a-9b2361364e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Buscar por producto, marca y más...</value>
      <webElementGuid>01acf0ce-0dce-4bc2-b9c8-8d6e1864bb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66dabee5-6bec-4111-983d-465dba1363de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar por producto, marca y más...</value>
      <webElementGuid>41325e3b-9f77-47d4-b2eb-f11a32244fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>678c0302-a8a3-4c9e-ad87-428edc9defe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>31f60ac1-bd8d-485b-8d57-84f75d8de0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sayt&quot;)/div[@class=&quot;m-header__searchBar&quot;]/div[@class=&quot;input-group&quot;]/input[@id=&quot;mainSearchbar&quot;]</value>
      <webElementGuid>66608e47-9683-45b0-a97f-83f806074f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainSearchbar']</value>
      <webElementGuid>0a496bbe-ae14-467a-8357-5a710157b6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sayt']/div/div/input</value>
      <webElementGuid>b9680cd3-6c84-4d22-9bad-9133ea40313f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>5d010f70-1e55-4114-85cc-fb9e786361e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mainSearchbar' and @type = 'text' and @placeholder = 'Buscar por producto, marca y más...']</value>
      <webElementGuid>386ca524-75bc-4f22-b765-f93bb0ba8803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
