<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo_hp</name>
   <tag></tag>
   <elementGuidId>5097d239-d080-4218-b9a3-de93d468e34c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.a-header__logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a/img[@class='a-header__logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>053230fb-2214-450b-8d11-66337082ff56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assetspwa.liverpool.com.mx/assets/images/logos/liverpool-logo.svg</value>
      <webElementGuid>61804180-4f2a-434f-bbc9-627a05b50559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-header__logo</value>
      <webElementGuid>90f3cfbf-e720-4a8e-9597-021514a7b905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Liverpool Logo</value>
      <webElementGuid>22928fa3-43fe-4fbd-b681-e42033c75fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Liverpool Logo</value>
      <webElementGuid>ea57b809-03ca-43e2-b909-09b3e1af92ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/header[1]/div[@class=&quot;o-header&quot;]/div[@class=&quot;o-container__fluid container-fluid&quot;]/div[@class=&quot;o-container container p-0&quot;]/div[@class=&quot;m-searchBar&quot;]/div[@class=&quot;o-checkout__header o-row row align-items-center no-gutters py-3 py-lg-2&quot;]/div[@class=&quot;o-col col-lg-auto col-6 order-2 order-lg-1 text-center min-width-logo&quot;]/a[1]/img[@class=&quot;a-header__logo&quot;]</value>
      <webElementGuid>3d8069c0-87c7-4b27-847b-ce75d3b1eda8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/header/div[4]/div[2]/div/div/div/div[2]/a/img</value>
      <webElementGuid>5df8fe04-6ee2-409f-b6f3-3043b67fb1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Liverpool Logo']</value>
      <webElementGuid>d0eb987c-b406-4adf-8108-0e793e13eb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>e591c49e-b461-495b-9420-047ba6688499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assetspwa.liverpool.com.mx/assets/images/logos/liverpool-logo.svg' and @alt = 'Liverpool Logo' and @title = 'Liverpool Logo']</value>
      <webElementGuid>b44afdbb-4b49-47b8-8067-fb4c51ff26c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
